# ===============================
# Application Name
# ===============================
spring.application.name=analytics_reporting-service

# ===============================
# Server
# ===============================
server.port=8087

# ===============================
# MySQL Database
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/edusphere_analytics_reporting_db
spring.datasource.username=root
spring.datasource.password=sony2005
# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# Swagger (Springdoc OpenAPI)
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
