server:
  port: 8088

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:mysql://localhost:3306/edusphere_analytics?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

app:
  jwt:
    secret: edusphere-jwt-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm
  service:
    secret: edusphere-internal-svc-2026
